(function(){
const D=window.LEARNING_ATLAS_DATA,E=window.LEARNING_ATLAS_ENHANCEMENTS,M=window.LEARNING_ATLAS_MATH;
if(!D||!E||!M)return;
const STORAGE="learning-atlas-course-levels-v1";
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||"{}")}catch(e){return {}}};
const write=x=>{try{localStorage.setItem(STORAGE,JSON.stringify(x))}catch(e){}};
const allChem=D.topics.map(t=>t.id), allMath=M.topics.map(t=>t.id);
const profiles={
 chemistry:{
  cp:{key:"cp",label:"CP",title:"Chemistry CP",subtitle:"Core Chemistry",description:"Concept-first chemistry with strong calculation fluency, laboratory reasoning, and deliberate scaffolding.",defaults:{count:15,grading:"lenient",feedback:"immediate",levels:{simple:45,medium:40,complex:15,fusion:0}},topics:allChem.filter(x=>!["entropy-free-energy","nuclear"].includes(x)),visuals:["density","displacement","sigfig","isotope","wave","molarity","gas","heat","ph","phase"],challengeMax:2},
  honors:{key:"honors",label:"Honors",title:"Chemistry Honors",subtitle:"Advanced High-School Chemistry",description:"Deeper quantitative reasoning, experimental analysis, cross-topic synthesis, and Honors-level problem solving.",defaults:{count:20,grading:"standard",feedback:"end",levels:{simple:15,medium:35,complex:35,fusion:15}},topics:allChem,visuals:["density","displacement","sigfig","isotope","wave","molarity","gas","heat","equilibrium","ph","kinetics","phase"],challengeMax:4},
  ap:{key:"ap",label:"AP",title:"AP Chemistry",subtitle:"College-Level General Chemistry",description:"AP-aligned chemistry emphasizing particulate models, quantitative relationships, data analysis, experimental evidence, equilibrium, kinetics, and thermodynamics.",defaults:{count:25,grading:"strict",feedback:"end",levels:{simple:5,medium:20,complex:40,fusion:35}},topics:[],visuals:["density","isotope","wave","molarity","gas","heat","equilibrium","ph","kinetics","phase"],challengeMax:4,official:"AP Chemistry · 9-unit framework"}
 },
 math:{
  cp:{key:"cp",label:"CP",title:"Mathematics CP",subtitle:"Algebra II",description:"Core Algebra II fluency with functions, equations, polynomials, exponentials, rational expressions, and foundational modeling.",defaults:{count:15,grading:"lenient",feedback:"immediate",levels:{simple:50,medium:35,complex:15,fusion:0}},topics:["functions","linear-systems","quadratics","complex","polynomial-algebra","polynomial-functions","radicals","rational-functions","exponential","logarithms","sequences","probability-data"],visuals:["parabola","transform","exponential","sequence","systems"],challengeMax:"Applied"},
  honors:{key:"honors",label:"Honors",title:"Mathematics Honors",subtitle:"Algebra II + Advanced Functions",description:"Honors Algebra II with advanced functions, trigonometry, analytic geometry, diagnostics, and multi-representation synthesis.",defaults:{count:20,grading:"standard",feedback:"end",levels:{simple:15,medium:35,complex:35,fusion:15}},topics:allMath,visuals:["parabola","transform","unit-circle","exponential","log","rational","sequence","systems"],challengeMax:"Challenge"},
  ap:{key:"ap",label:"AP",title:"AP Precalculus",subtitle:"Functions, Modeling & Trigonometry",description:"AP Precalculus-aligned work centered on polynomial/rational, exponential/logarithmic, and trigonometric/polar functions with modeling across representations.",defaults:{count:25,grading:"strict",feedback:"end",levels:{simple:5,medium:20,complex:40,fusion:35}},topics:["functions","quadratics","polynomial-algebra","polynomial-functions","rational-functions","exponential","logarithms","trig-foundations","trig-functions","advanced-modeling"],visuals:["parabola","transform","unit-circle","exponential","log","rational","systems"],challengeMax:"Challenge",official:"AP Precalculus · Units 1–3 exam-aligned"}
 }
};

/* AP extension modules are real usable content, not placeholders. */
if(!D.topics.some(t=>t.id==="ap-chemistry-evidence")){
 D.topics.push({id:"ap-chemistry-evidence",name:"AP Quantitative & Experimental Reasoning",description:"AP-style evidence, representations, equilibrium calculations, and experimental argumentation.",modules:[
  {id:"ap-particulate",name:"Particulate Representations",type:"AP Core",summary:"Translate among symbolic, macroscopic, and particulate views.",learn:"AP Chemistry repeatedly asks students to connect equations and measurements to particle-level structure. A strong explanation names the particles, their relative amounts, and the interaction or process causing the observation.",example:"A conductivity increase after adding a soluble ionic compound is explained by a larger concentration of mobile ions, not simply by saying the solution became more concentrated.",practice:[["A diagram shows twice as many dissolved ions after a change. What macroscopic property could rise?","Electrical conductivity"],["Why is a balanced equation not enough to describe a solution microscopically?","It does not by itself show dissociation, solvation, or relative particle populations."],["What should a particulate explanation connect?","Observable evidence to particle identity, quantity, arrangement, or interaction."]]},
  {id:"ap-equilibrium-calc",name:"Quantitative Equilibrium",type:"AP Core",summary:"Use K, Q, ICE reasoning, and coupled equilibrium logic.",learn:"AP equilibrium work moves beyond direction-of-shift reasoning. Students must construct equilibrium expressions, compare Q with K, and solve for equilibrium concentrations while justifying approximations when used.",example:"For A⇌B with K=4.0 and initial [A]=1.0 M, [B]=0, an ICE table gives K=x/(1−x)=4, so x=0.80 M.",practice:[["If Q<K, which net direction is favored?","Forward"],["What information belongs in an ICE table?","Initial, change, and equilibrium concentrations or pressures."],["When is a small-x approximation defensible?","When the resulting change is small relative to the initial amount and the approximation is checked."]]},
  {id:"ap-data-evidence",name:"Data, Error & Evidence",type:"AP Practice",summary:"Interpret graphs, uncertainty, controls, and experimental claims.",learn:"AP scientific practice rewards conclusions supported by specific evidence. Identify the trend, quantify it when possible, consider uncertainty or uncontrolled variables, and connect the evidence to a chemical model.",example:"If rate doubles when [A] doubles while other concentrations stay fixed, the data support first-order dependence on A.",practice:[["What makes a conclusion stronger than 'the graph goes up'?","Quantifying the trend and linking it to the chemical claim."],["Why include a control?","To isolate the effect of the independent variable."],["What should be done with an outlier?","Investigate its experimental basis before deciding whether exclusion is justified."]]},
  {id:"ap-frq-reasoning",name:"AP Free-Response Reasoning",type:"AP Practice",summary:"Write concise claim-evidence-reasoning responses.",learn:"A high-quality AP response answers the command verb directly, uses relevant chemical evidence, and explains the causal relationship. More writing is not automatically better; chemically precise reasoning is.",example:"Claim: increasing temperature raises the rate. Evidence: a larger fraction of collisions exceed Ea. Reasoning: more successful collisions per unit time increase reaction rate.",practice:[["For 'justify,' what must follow the answer?","Relevant chemical evidence or a principle explaining why."],["For 'calculate,' what should still be shown?","Setup, substitution, and a defensible result with units when applicable."],["For 'predict and explain,' what two parts are required?","A directional prediction and the chemical reasoning supporting it."]]}
 ]});
}
if(!M.topics.some(t=>t.id==="ap-precalc-extensions")){
 M.topics.push({id:"ap-precalc-extensions",name:"AP Precalculus Extensions",description:"AP-specific function modeling, covariation, polar functions, and multiple-representation reasoning.",modules:[
  {id:"ap-covariation",name:"Covariation & Rates of Change",type:"AP Core",summary:"Reason about how two quantities vary together across intervals.",learn:"AP Precalculus emphasizes describing and comparing how output changes as input changes. Average rate of change, concavity, and relative change help distinguish model families.",example:"If equal x-intervals produce approximately constant output ratios, an exponential model is structurally plausible.",practice:[["What does average rate of change measure?","Change in output divided by change in input over an interval."],["Constant second differences suggest which family?","Quadratic/polynomial of degree two."],["Constant ratios suggest which family?","Exponential."]]},
  {id:"ap-rational-models",name:"Polynomial & Rational Modeling",type:"AP Unit 1",summary:"Use zeros, end behavior, asymptotes, and rates to model contexts.",learn:"AP work asks students to select, build, and interpret polynomial or rational models using multiple representations. Parameters should be interpreted in context, not treated as decoration.",example:"A rational model approaching y=80 may represent a quantity saturating near 80 units, so the horizontal asymptote has contextual meaning.",practice:[["What feature can encode a long-run limiting value?","A horizontal asymptote."],["What does multiplicity influence graphically?","How a polynomial meets or crosses an x-intercept."],["Why inspect end behavior?","To judge long-run model behavior and plausibility."]]},
  {id:"ap-polar",name:"Polar Functions",type:"AP Unit 3",summary:"Interpret radius as a function of angle and connect polar graphs to periodic behavior.",learn:"In polar coordinates, a point is located by angle θ and signed radial distance r. AP Precalculus connects polar functions to periodicity, symmetry, rates, and graphical interpretation.",example:"r=2+2cosθ produces a cardioid-like curve whose radial distance changes periodically with θ.",practice:[["What do polar coordinates use instead of x and y directly?","Angle and radial distance."],["If r is negative, how is the point plotted?","In the direction opposite the given angle."],["Why are trig functions natural in polar models?","The independent variable is angular and many radial patterns are periodic."]]},
  {id:"ap-multiple-reps",name:"AP Multiple Representations",type:"AP Practice",summary:"Move deliberately among formulas, graphs, tables, and contextual statements.",learn:"AP Precalculus questions frequently require one representation to justify a conclusion about another. The skill is not just graphing but identifying which representation makes a feature easiest to establish.",example:"A table of values may show near-constant ratios more clearly than an equation written in an unfamiliar transformed form.",practice:[["Which representation often exposes zeros fastest?","Factored form or an x-intercept graph."],["Which representation can reveal residual pattern?","A residual plot."],["Why compare representations?","Each representation exposes different structural information."]]}
 ]});
}
profiles.chemistry.ap.topics=[...allChem.filter(x=>!["nuclear"].includes(x)),"ap-chemistry-evidence"];
profiles.math.ap.topics=[...profiles.math.ap.topics,"ap-precalc-extensions"];

/* Supplemental original AP-style questions. They are not copied from College Board. */
const Q=(q,options,answer,why,topic,difficulty="complex")=>({q,options,answer,why,topic,difficulty,courseLevels:["ap"]});
const chemAP=[
 Q("A reaction rate doubles when [A] doubles while all other conditions are fixed. The data best support which order in A?",["zero","first","second","cannot infer"],1,"A doubling of concentration causing a doubling of rate supports first-order dependence.","Kinetics"),
 Q("For a reaction with Q<K, which statement is most defensible?",["Net reaction proceeds toward reactants","Net reaction proceeds toward products","System is necessarily at equilibrium","K decreases"],1,"Q<K means the current product-to-reactant ratio is below the equilibrium ratio.","Equilibrium"),
 Q("For HA⇌H⁺+A⁻, which expression represents Ka?",["[HA]/([H⁺][A⁻])","[H⁺][A⁻]/[HA]","[H⁺]/[A⁻]","[A⁻]/[H⁺]"],1,"Products over reactant, each raised to stoichiometric powers.","Acid-base"),
 Q("A buffer contains comparable amounts of HA and A⁻. Added H⁺ is primarily consumed by?",["HA","A⁻","water only","an inert ion"],1,"The conjugate base component A⁻ consumes added H⁺.","Acid-base"),
 Q("Which observation most directly supports stronger intermolecular attractions?",["Higher vapor pressure","Lower boiling point","Higher boiling point","Lower molar mass"],2,"Stronger attractions require more energy to separate molecules.","Bonding"),
 Q("A gas sample is heated at constant volume. Which microscopic change explains increased pressure?",["Particles become larger","Average kinetic energy and collision impulse increase","Moles decrease","Attractions become dominant"],1,"Higher temperature raises average kinetic energy and wall-collision effects.","Gases"),
 Q("A catalyst is added to a reaction at equilibrium. Which quantity changes?",["K","ΔG°","Forward and reverse rates","Equilibrium composition"],2,"A catalyst lowers activation barriers for both directions without changing thermodynamic equilibrium.","Kinetics"),
 Q("A calorimetry experiment loses heat to the room. If the reaction is exothermic, the magnitude of calculated ΔH is likely?",["too large","too small","unchanged","opposite sign"],1,"Some released heat is not measured by the intended calorimeter system.","Thermochemistry"),
 Q("If a student doubles both reactant coefficients in a thermochemical equation, ΔH should be?",["halved","unchanged","doubled","squared"],2,"Enthalpy is extensive and scales with the reaction amount.","Thermochemistry"),
 Q("Which statement about spontaneous reactions is correct?",["They must be fast","They have ΔG<0 under the stated conditions","They require Ea=0","They cannot be reversible"],1,"Thermodynamic favorability does not determine rate.","Free energy"),
 Q("A strong electrolyte and weak electrolyte have equal formal concentration. Which typically has higher conductivity?",["Weak electrolyte","Strong electrolyte","They must be equal","Neither conducts"],1,"The strong electrolyte produces a larger concentration of mobile ions.","Solutions"),
 Q("Why can a titration curve identify pKa for a weak monoprotic acid?",["pKa equals volume","At half-equivalence pH≈pKa","At equivalence pH is always 7","Indicator color equals Ka"],1,"At half-equivalence [HA]=[A⁻], so Henderson-Hasselbalch gives pH=pKa.","Acid-base"),
 Q("For an exothermic equilibrium, increasing temperature generally shifts equilibrium?",["toward products","toward reactants","not at all","K becomes zero"],1,"Heat can be treated as a product for qualitative Le Châtelier reasoning.","Equilibrium"),
 Q("Which plot can support first-order kinetics?",["[A] vs t linear","ln[A] vs t linear","1/[A] vs t always curved","rate vs mass only"],1,"Integrated first-order kinetics gives ln[A]=−kt+ln[A]₀.","Kinetics"),
 Q("A student claims a 2% difference proves two methods disagree. What additional information is most important?",["Color of glassware","Measurement uncertainty/precision","Molar mass only","Room number"],1,"The difference must be interpreted relative to uncertainty and experimental resolution.","Lab data"),
 Q("Which particulate diagram best represents a saturated solution with undissolved solid?",["Only solvent particles","Dissolved solute plus remaining solid phase","All solute removed","Gas particles only"],1,"At saturation, dissolved solute is in dynamic equilibrium with undissolved solute.","Solubility"),
 Q("An endothermic dissolution cools the solution. Which sign is appropriate for ΔHsolution?",["negative","positive","zero","undefined"],1,"The process absorbs heat from surroundings.","Thermochemistry"),
 Q("For a galvanic cell, which relationship is correct?",["Oxidation at cathode","Reduction at anode","Electrons flow anode to cathode","Salt bridge carries electrons"],2,"Electrons leave the oxidation half-cell and travel to the reduction half-cell.","Electrochem"),
 Q("Increasing ionic charge while keeping size similar generally makes lattice interactions?",["weaker","stronger","unchanged","non-electrostatic"],1,"Electrostatic attraction magnitude increases with charge product.","Bonding"),
 Q("A molecule has polar bonds but zero net dipole. Best explanation?",["Bonds are actually ionic","Symmetric geometry cancels bond dipoles","Electrons are absent","Temperature is zero"],1,"Molecular geometry determines vector cancellation of bond dipoles.","Bonding"),
 Q("Which change directly increases entropy in a typical process?",["Gas condenses","Solid forms from liquid","Gas expands into larger volume","Particles become more constrained"],2,"Greater dispersal and accessible microstates increase entropy.","Entropy"),
 Q("An equilibrium expression omits a pure liquid because its activity is treated as?",["zero","constant","infinite","negative"],1,"Pure solids and liquids have effectively constant activity in the equilibrium expression.","Equilibrium"),
 Q("A reaction mechanism proposes a slow elementary step. That step most directly influences?",["overall rate law","equilibrium constant only","molar mass","heat capacity"],0,"The rate-determining step often controls the observed rate dependence.","Kinetics"),
 Q("In a Beer-Lambert style relationship, absorbance increasing linearly with concentration supports using absorbance to?",["infer concentration","infer neutron count","measure pressure only","change wavelength automatically"],0,"A calibrated linear relationship lets absorbance serve as a concentration proxy.","AP Experimental"),
 Q("A calibration curve has one point far from the trend. Best AP-style action?",["Delete it immediately","Investigate procedure/instrument before deciding","Move it onto the line","Average only that point"],1,"Outlier treatment should be evidence-based.","AP Experimental"),
 Q("If K is very large, equilibrium generally favors?",["reactants","products","equal amounts necessarily","no reaction"],1,"Large K corresponds to a product-favored equilibrium mixture.","Equilibrium"),
 Q("If ΔG° is negative, K is generally?",["less than 1","greater than 1","exactly 0","unrelated"],1,"ΔG°=−RT lnK links negative ΔG° with K>1.","Free energy"),
 Q("A weak acid is diluted. Percent ionization generally?",["decreases to zero","increases","stays exactly fixed","becomes 100% always"],1,"Dilution often increases percent ionization even while [H⁺] decreases.","Acid-base"),
 Q("Why should an AP calculation retain guard digits?",["To make work longer","To reduce accumulated rounding error","Because units disappear","To change significant figures"],1,"Round once at the end unless intermediate reporting is requested.","Measurement"),
 Q("For 2A→B, disappearance rate of A compared with formation rate of B is?",["half as large","twice as large","equal numerically without coefficients","unrelated"],1,"Stoichiometric rate definitions account for coefficient 2.","Kinetics"),
 Q("A precipitate forms when ion product exceeds Ksp. This means Q is?",["<Ksp","=0",">Ksp","unrelated"],2,"Supersaturation Q>Ksp drives precipitation toward equilibrium.","Equilibrium"),
 Q("Which evidence best supports a chemical reaction?",["Only temperature is measured","Formation of a new substance supported by composition/particle evidence","A container is moved","Mass is written in grams"],1,"Macroscopic changes are strongest when linked to evidence of new chemical species.","Reactions"),
 Q("Why can bond formation release energy?",["Attractive interactions lower potential energy","Atoms gain mass","Electrons stop moving","Temperature must fall"],0,"Stable bonded arrangements can have lower potential energy than separated particles.","Bonding"),
 Q("Which statement about an AP FRQ 'justify' prompt is strongest?",["State an answer only","Give a relevant principle/evidence that connects to the conclusion","Write every formula known","Repeat the prompt"],1,"Justification requires reasoning or evidence, not just the result.","AP Experimental"),
 Q("When comparing two possible models for data, which is most useful?",["Number of letters in equation","Residual structure plus contextual plausibility","Largest coefficient","Most complex formula"],1,"A good model fits residual behavior and makes sense in context.","AP Experimental"),
 Q("A reaction has favorable ΔG but high Ea. Which combination is expected?",["Fast and nonspontaneous","Thermodynamically favorable but kinetically slow","Impossible reaction","Equilibrium constant zero"],1,"Thermodynamics and kinetics answer different questions.","Fusion","fusion")
];
const mathAP=[
 Q("A polynomial model has a repeated zero at x=2. Which local behavior is consistent?",["Crosses sharply","Touches/turns or flattens depending on even multiplicity","Vertical asymptote","Hole only"],1,"Even multiplicity typically causes the graph to touch and turn.","Polynomial Functions"),
 Q("A rational function approaches y=5 as x grows without bound. In context, y=5 can represent?",["A vertical asymptote","A long-run limiting value","A zero","A domain restriction only"],1,"Horizontal asymptotes often encode limiting behavior in models.","Rational Functions"),
 Q("Equal input increments produce approximately equal output ratios. Best model family?",["Linear","Quadratic","Exponential","Constant"],2,"Constant multiplicative change supports exponential structure.","Exponential"),
 Q("For f(x)=ab^x with b>1, increasing b while keeping a fixed generally makes long-run growth?",["slower","faster","linear","periodic"],1,"A larger multiplicative factor compounds more rapidly.","Exponential"),
 Q("If log_b(x)=y, which equivalent statement is correct?",["x^b=y","b^y=x","y^x=b","b+x=y"],1,"Logarithmic and exponential forms are inverse descriptions.","Logarithms"),
 Q("A sinusoidal model has period 8. What is B in A sin(Bx)+D?",["π/8","π/4","4π","8π"],1,"B=2π/8=π/4.","Trig Functions"),
 Q("A context repeats every 24 hours. Which feature should a periodic model encode?",["A zero denominator","Period 24","Constant ratio only","A vertical asymptote"],1,"Period matches the repeat interval.","Trig Functions"),
 Q("Why might a transformed function be preferable to fitting an entirely new family?",["Transformations preserve core family structure while adjusting features","It always has fewer terms","It removes domains","It avoids interpretation"],0,"Transformation parameters can encode shifts/scales while retaining known behavior.","Functions"),
 Q("Average rate of change over [a,b] equals?",["f(a)+f(b)","[f(b)−f(a)]/(b−a)","f(b)/f(a) always","b−a"],1,"It is secant slope over the interval.","AP Precalculus"),
 Q("If a function is increasing but at a decreasing rate, its graph can be described as?",["Increasing with decreasing slopes","Constant","Decreasing with increasing slopes","Periodic necessarily"],0,"Outputs rise while successive rates of change decline.","AP Precalculus"),
 Q("A polynomial's end behavior is determined primarily by?",["All coefficients equally","Leading term","Constant term only","Smallest exponent"],1,"For large |x| the leading term dominates.","Polynomial Functions"),
 Q("For f(x)=(x−3)/(x+2), the vertical asymptote is?",["x=3","x=−2","y=1","y=−2"],1,"Uncanceled denominator zero gives the vertical asymptote.","Rational Functions"),
 Q("For equal-degree rational numerator and denominator, horizontal asymptote is found from?",["Constant terms","Ratio of leading coefficients","Zeros only","Derivative"],1,"Leading behavior controls the end-behavior ratio.","Rational Functions"),
 Q("If an exponential model doubles every 5 units, one form is?",["a+2x/5","a·2^(x/5)","a·5^(x/2)","a/x"],1,"Every five input units multiplies by two.","Exponential"),
 Q("A logarithmic scale changes by 3 units base 10. Underlying multiplicative change is?",["3","10","100","1000"],3,"Three base-10 log units correspond to 10^3.","Logarithms"),
 Q("On the unit circle, cosθ corresponds to?",["y-coordinate","x-coordinate","radius only","arc length"],1,"Coordinates are (cosθ,sinθ).","Trig Foundations"),
 Q("A polar function uses which pair?",["slope and intercept","radius and angle","x and y only","mean and SD"],1,"Polar coordinates use radial distance r and angle θ.","AP Precalculus"),
 Q("If r is negative in polar coordinates, the point lies?",["At origin always","Opposite the direction of θ by |r|","On x-axis only","Undefined"],1,"Negative radial distance reverses direction.","AP Precalculus"),
 Q("A table shows outputs 4, 8, 16, 32 at equal input steps. Relative change is?",["Add 4","Multiply by 2","Square each time","Subtract 2"],1,"Each output doubles.","Exponential"),
 Q("For a model that saturates toward a finite ceiling, which feature is useful?",["Horizontal asymptote","Repeated root only","Constant second difference","Undefined domain everywhere"],0,"The asymptote can encode the limiting value.","Rational Functions"),
 Q("A zero at x=4 with multiplicity 3 contributes factor?",["(x+4)^3","(x−4)^3","3(x−4)","x³−4"],1,"Root r gives factor (x−r) with exponent equal to multiplicity.","Polynomial Functions"),
 Q("If f and f⁻¹ intersect, their intersection lies on?",["x-axis","y=x","y-axis","y=−x"],1,"Inverse graphs reflect across y=x.","Functions"),
 Q("Which representation best reveals a polynomial's zeros?",["Factored form","Standard expanded form always","A verbal description only","Random table"],0,"Factored form exposes roots directly.","Polynomial Functions"),
 Q("Which representation best reveals an exponential growth factor?",["Successive output ratios or a form ab^x","Second differences","x-intercepts only","Polar radius"],0,"Constant ratios identify multiplicative change.","Exponential"),
 Q("A residual plot with curvature after linear regression suggests?",["Linear model captures all structure","Nonlinear structure remains","Causation","No measurement error"],1,"Systematic residual patterns indicate model misspecification.","Modeling"),
 Q("A model has excellent fit on observed data but impossible long-run behavior. Best conclusion?",["Ignore context","Limit use/extrapolation or choose a more plausible model","Fit guarantees future validity","Delete data"],1,"Model validity includes contextual and extrapolation behavior.","Modeling"),
 Q("If y=A cos(B(x−C))+D, C controls?",["Amplitude","Period directly","Horizontal shift","Midline"],2,"C is the phase/horizontal shift.","Trig Functions"),
 Q("For a periodic function, adding one full period to input does what?",["Changes output unpredictably","Returns same output","Makes output zero","Changes domain"],1,"Periodic functions repeat after each period.","Trig Functions"),
 Q("A student's model uses degrees in a formula derived for radian angular rate. What is the main issue?",["Units/scale are inconsistent","Graph becomes rational","No effect ever","Domain becomes empty"],0,"Angular measure must match the model's rate definition.","Trig Foundations"),
 Q("A polynomial and rational model both fit current data. Which evidence can help distinguish them?",["Long-run/end behavior and residuals","Font size","Number of variables only","Color"],0,"Structural behavior beyond current points can distinguish models.","Modeling"),
 Q("AP Precalculus multiple representations commonly include?",["Only symbolic equations","Graphical, numerical, analytical, and verbal/contextual views","Only geometry","Only calculators"],1,"The course emphasizes interpreting and connecting representations.","AP Precalculus"),
 Q("A context's output changes from 100 to 120 to 144 at equal intervals. Percent growth per interval?",["12%","20%","24%","44%"],1,"Each value is multiplied by 1.20.","Exponential"),
 Q("For y=3sin(2x)+1, midline and amplitude are?",["midline 3, amplitude 1","midline 1, amplitude 3","midline 2, amplitude 3","midline 1, amplitude 2"],1,"D=1 is midline and |A|=3 is amplitude.","Trig Functions"),
 Q("A rational model has a hole at x=2. This indicates?",["An original domain exclusion caused by a canceled factor","A vertical asymptote must also be x=2","A maximum","The function is polynomial"],0,"Canceled common factors leave removable discontinuities.","Rational Functions"),
 Q("Why is an AP 'justify' response stronger when it references a graph feature explicitly?",["It connects evidence to the conclusion","It adds length only","It removes need for reasoning","Graphs are always exact"],0,"Specific evidence supports the claim.","AP Precalculus"),
 Q("A function's average rate of change changes sign from positive to negative around x=3. This can signal?",["A local maximum near x=3","No turning point possible","A vertical asymptote necessarily","Constant function"],0,"Increasing then decreasing behavior is consistent with a local maximum.","AP Precalculus","fusion")
];

const storageLevel=subject=>read()[subject]||"honors";
const setLevel=(subject,level)=>{if(!profiles[subject]?.[level])return;const x=read();x[subject]=level;write(x)};
const getProfile=(subject,level=storageLevel(subject))=>profiles[subject]?.[level]||profiles[subject]?.honors;
const topicIds=(subject,level)=>getProfile(subject,level).topics;
const topicAllowed=(subject,id,level)=>topicIds(subject,level).includes(id);
const visuals=(subject,level)=>getProfile(subject,level).visuals;

const flatten=(tests,subject)=>{const diff={A:"simple",B:"simple",C:"medium",D:"complex",E:"complex",F:"fusion"};const out=[];Object.entries(tests||{}).forEach(([k,t])=>(t.questions||[]).forEach((q,i)=>out.push({...q,id:subject+"-"+k+"-"+i,difficulty:q.difficulty||diff[k]||"medium",sourceTest:k,courseLevels:q.courseLevels||["cp","honors","ap"]})));return out};
const pool=(subject,level=storageLevel(subject))=>{
 const base=subject==="chemistry"?flatten(E.practiceTests,"chemistry"):flatten(M.practiceTests,"math");
 const extra=(subject==="chemistry"?chemAP:mathAP).map((q,i)=>({...q,id:subject+"-ap-"+i}));
 const prof=getProfile(subject,level), allowedTopics=new Set(prof.topics);
 const keywordOk=q=>{
   if(level!=="ap")return true;
   const t=(q.topic||"").toLowerCase();
   if(subject==="chemistry")return true;
   return !["probability","counting","sequences","conics","analytic geometry"].some(x=>t.includes(x));
 };
 return base.concat(level==="ap"?extra:[]).filter(q=>(!q.courseLevels||q.courseLevels.includes(level))&&keywordOk(q));
};
const seedHash=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0};
const shuffled=(arr,seed)=>{let x=seed>>>0;const r=()=>{x=(1664525*x+1013904223)>>>0;return x/4294967296};const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const allocation=(n,mix)=>{const keys=["simple","medium","complex","fusion"],a=keys.map(k=>({k,raw:n*(mix[k]||0)/100}));let used=0;a.forEach(x=>{x.n=Math.floor(x.raw);x.fr=x.raw-x.n;used+=x.n});a.sort((x,y)=>y.fr-x.fr);for(let i=0;used<n;i++,used++)a[i%a.length].n++;return Object.fromEntries(a.map(x=>[x.k,x.n]))};
const choose=(p,n,mix,seed,used=new Set())=>{const want=allocation(n,mix),out=[];["simple","medium","complex","fusion"].forEach((d,di)=>{let c=shuffled(p.filter(q=>q.difficulty===d&&!used.has(q.id)),seed+di*101);for(let i=0;i<(want[d]||0)&&i<c.length;i++){out.push(c[i]);used.add(c[i].id)}});if(out.length<n){for(const q of shuffled(p.filter(q=>!used.has(q.id)),seed+909)){if(out.length>=n)break;out.push(q);used.add(q.id)}}if(out.length<n){for(const q of shuffled(p,seed+1909)){if(out.length>=n)break;out.push(q)}}return shuffled(out,seed+2909)};
const testBlueprints={
 cp:[
  ["Test 1 · Foundations","Definitions, direct calculation, and core notation",{simple:70,medium:25,complex:5,fusion:0}],
  ["Test 2 · Core Skills","One- and two-step course skills",{simple:50,medium:40,complex:10,fusion:0}],
  ["Test 3 · Applied","Use core ideas in less familiar settings",{simple:25,medium:55,complex:20,fusion:0}],
  ["Test 4 · Mixed","Switch among topics and representations",{simple:20,medium:45,complex:30,fusion:5}],
  ["Test 5 · Cumulative","Broad-course review with diagnostics",{simple:20,medium:40,complex:35,fusion:5}],
  ["Test 6 · Course Challenge","The strongest CP-level reasoning set",{simple:10,medium:35,complex:45,fusion:10}]
 ],
 honors:[
  ["Test 1 · Foundations","Fast fluency before deeper reasoning",{simple:55,medium:35,complex:10,fusion:0}],
  ["Test 2 · Core Skills","Multi-step procedures and representations",{simple:30,medium:50,complex:20,fusion:0}],
  ["Test 3 · Applied","Transfer concepts into unfamiliar forms",{simple:15,medium:45,complex:35,fusion:5}],
  ["Test 4 · Honors","Hidden setup and diagnostic reasoning",{simple:5,medium:25,complex:55,fusion:15}],
  ["Test 5 · Cumulative","Broad mixed-topic Honors review",{simple:10,medium:25,complex:45,fusion:20}],
  ["Test 6 · Fusion","Cross-topic synthesis where method selection matters",{simple:0,medium:10,complex:35,fusion:55}]
 ],
 ap:[
  ["Test 1 · AP Foundations","Required foundations with AP-level interpretation",{simple:15,medium:45,complex:35,fusion:5}],
  ["Test 2 · AP Applications","Quantitative and representation-heavy applications",{simple:5,medium:35,complex:50,fusion:10}],
  ["Test 3 · Data & Modeling","Evidence, graphs, multiple representations, and models",{simple:5,medium:25,complex:50,fusion:20}],
  ["Test 4 · Complex Reasoning","Multi-step work with limited scaffolding",{simple:0,medium:15,complex:60,fusion:25}],
  ["Test 5 · AP Cumulative","Broad AP-aligned cumulative practice",{simple:0,medium:15,complex:50,fusion:35}],
  ["Test 6 · AP Fusion","Cross-unit synthesis and exam-style reasoning",{simple:0,medium:5,complex:35,fusion:60}]
 ]
};
const curatedTests=(subject,level=storageLevel(subject))=>{const p=pool(subject,level),used=new Set(),bp=testBlueprints[level];const o={};bp.forEach((b,i)=>{o["L"+(i+1)]={title:b[0],subtitle:b[1],questions:choose(p,18,b[2],seedHash(subject+level+i),used)}});return o};
const mocks=(subject,level=storageLevel(subject))=>{const p=pool(subject,level),prof=getProfile(subject,level),mix=prof.defaults.levels;const count=level==="ap"?30:24;return {M1:{title:"Mock 1 · Mixed Course",subtitle:"Broad content and representation switching",questions:choose(p,count,mix,seedHash(subject+level+"m1"))},M2:{title:"Mock 2 · Application",subtitle:"Less scaffolding and more transfer",questions:choose(p,count,{simple:level==="cp"?15:5,medium:level==="ap"?20:35,complex:level==="cp"?45:45,fusion:level==="ap"?35:5},seedHash(subject+level+"m2"))},M3:{title:"Mock 3 · Synthesis",subtitle:level==="ap"?"AP-style complex and cross-unit reasoning":"Cumulative challenge and diagnostics",questions:choose(p,count,{simple:level==="cp"?10:0,medium:level==="cp"?35:15,complex:level==="cp"?45:50,fusion:level==="cp"?10:35},seedHash(subject+level+"m3"))}}};

window.LEARNING_ATLAS_LEVELS={version:"1.0",profiles,getLevel:storageLevel,setLevel,getProfile,topicIds,topicAllowed,visuals,pool,curatedTests,mocks,apSupplemental:{chemistry:chemAP.length,math:mathAP.length}};
})();