(function(){
const D=window.LEARNING_ATLAS_DATA, E=window.LEARNING_ATLAS_ENHANCEMENTS;
const moreTopics=[
{id:"periodic-electrons",name:"Periodic Table & Electron Structure",description:"Periodic trends, valence electrons, electron configurations, orbital ideas, and periodic reasoning.",modules:[
{id:"periodic-trends",name:"Periodic Trends",type:"Conceptual",summary:"Predict radius, ionization energy, and electronegativity from periodic position.",learn:"Across a period, effective nuclear charge generally increases. Down a group, additional energy levels increase atomic size.",example:"Atomic radius generally decreases left→right and increases top→bottom.",practice:[["Which is larger, Na or Cl?","Na"],["Which generally has higher ionization energy, Mg or Cl?","Cl"],["Why does radius increase down a group?","Additional occupied energy levels increase distance and shielding."]]},
{id:"electron-config",name:"Electron Configuration",type:"Representation",summary:"Translate electron counts into shells, subshells, and configurations.",learn:"Electrons occupy lower-energy orbitals first, with orbital capacity governed by the Pauli principle and Hund's rule.",example:"Na: 1s² 2s² 2p⁶ 3s¹.",practice:[["Electron configuration of O?","1s² 2s² 2p⁴"],["How many valence electrons does Na have?","1"],["Why do elements in one group behave similarly?","They have similar valence-electron patterns."]]},
{id:"ions-periodicity",name:"Ions & Periodicity",type:"Reasoning",summary:"Connect ion formation to stable electron arrangements and ionic size.",learn:"Metals often lose valence electrons to form cations; nonmetals often gain electrons to form anions.",example:"Na → Na⁺ + e⁻; Cl + e⁻ → Cl⁻.",practice:[["Which is smaller, Na or Na⁺?","Na⁺"],["Which is larger, Cl or Cl⁻?","Cl⁻"],["Why do cations often shrink?","Electron loss can remove an outer shell and reduce electron-electron repulsion."]]}
]},
{id:"formulas-nomenclature",name:"Chemical Formulas & Nomenclature",description:"Ionic compounds, molecular compounds, acids, polyatomic ions, and translating names to formulas.",modules:[
{id:"ionic-formulas",name:"Ionic Formulas",type:"Representation",summary:"Balance ionic charges to create neutral formulas.",learn:"A stable ionic formula has total positive charge equal to total negative charge.",example:"Al³⁺ and O²⁻ combine as Al₂O₃.",practice:[["Formula for Mg²⁺ and Cl⁻?","MgCl₂"],["Formula for Al³⁺ and SO₄²⁻?","Al₂(SO₄)₃"],["Why are subscripts reduced to lowest whole-number ratio?","The formula represents the simplest neutral ratio of ions."]]},
{id:"compound-names",name:"Naming Compounds",type:"Language",summary:"Name ionic and molecular compounds using systematic rules.",learn:"Ionic names identify cation then anion; molecular compounds use prefixes to indicate atom counts.",example:"FeCl₃ is iron(III) chloride; N₂O₅ is dinitrogen pentoxide.",practice:[["Name CaBr₂.","Calcium bromide"],["Name CO₂.","Carbon dioxide"],["Why is a Roman numeral used for many transition metals?","It identifies the metal's ionic charge."]]},
{id:"formula-translation",name:"Name ↔ Formula Translation",type:"Multi-step",summary:"Move accurately between chemical names, ion charges, and formulas.",learn:"Identify species and charges first, construct a neutral formula, then verify atom counts and parentheses.",example:"Ammonium sulfate → (NH₄)₂SO₄.",practice:[["Formula for calcium nitrate?","Ca(NO₃)₂"],["Name Cu₂O.","Copper(I) oxide"],["Why are parentheses required in Ca(NO₃)₂?","The subscript 2 applies to the entire nitrate ion."]]}
]},
{id:"bonding",name:"Chemical Bonding & Molecular Structure",description:"Ionic, covalent, and metallic bonding; Lewis structures; polarity; intermolecular forces.",modules:[
{id:"bond-types",name:"Bond Types",type:"Conceptual",summary:"Distinguish ionic, covalent, and metallic bonding models.",learn:"Ionic bonding involves electrostatic attraction between ions; covalent bonding shares electron pairs; metallic bonding involves delocalized electrons.",example:"NaCl ionic, H₂O covalent, Cu metallic.",practice:[["Bonding in MgO?","Ionic"],["Bonding within O₂?","Covalent"],["Why do metals conduct well?","Delocalized electrons can move through the structure."]]},
{id:"lewis-structures",name:"Lewis Structures",type:"Representation",summary:"Track valence electrons and bonding pairs.",learn:"Count valence electrons, choose a skeleton, form bonds, complete octets where appropriate, then check total electrons and formal charges.",example:"CO₂ is O=C=O with two lone pairs on each oxygen.",practice:[["Total valence electrons in H₂O?","8"],["Why can double bonds appear?","They can satisfy octets while using the available valence electrons."],["What should be checked last?","Total electrons and reasonable formal charges."]]},
{id:"polarity-imf",name:"Polarity & Intermolecular Forces",type:"Reasoning",summary:"Connect bond polarity and shape to molecular attractions and physical properties.",learn:"Molecular polarity depends on bond dipoles and geometry. Stronger intermolecular attractions often raise boiling point.",example:"H₂O is polar and forms hydrogen bonds.",practice:[["Is CO₂ polar overall?","No"],["Strongest common IMF between water molecules?","Hydrogen bonding"],["Why can two polar bonds produce a nonpolar molecule?","Bond dipoles can cancel because of molecular symmetry."]]}
]},
{id:"states-matter",name:"States of Matter & Phase Change",description:"Particle models, phase diagrams, vapor pressure, intermolecular forces, and energy during phase transitions.",modules:[
{id:"particle-phases",name:"Particle Models of Phases",type:"Visual Reasoning",summary:"Explain solids, liquids, and gases microscopically.",learn:"Solids have constrained particles, liquids have close but mobile particles, and gases have widely separated rapidly moving particles.",example:"A liquid flows because particles can rearrange while remaining close together.",practice:[["Most compressible phase?","Gas"],["Why does a solid keep shape?","Particles are strongly constrained around fixed positions."],["Do particles stop moving in a solid?","No; they still vibrate."]]},
{id:"phase-change",name:"Heating Curves & Phase Change",type:"Graph Reasoning",summary:"Interpret temperature plateaus and energy flow.",learn:"During a phase change, added energy changes intermolecular organization rather than temperature.",example:"At a boiling plateau, temperature can stay constant while vaporization proceeds.",practice:[["What happens to temperature during an ideal melting plateau?","It remains constant."],["Where does added energy go during vaporization?","Into overcoming intermolecular attractions."],["Which requires more energy for water: melting or vaporizing equal mass?","Vaporizing."]]},
{id:"phase-diagrams",name:"Phase Diagrams",type:"Data Analysis",summary:"Read regions, boundaries, triple points, and critical points.",learn:"Each region represents a stable phase; boundary lines represent equilibrium between phases.",example:"The triple point is where solid, liquid, and gas can coexist at equilibrium.",practice:[["What does crossing a liquid-gas boundary represent?","Vaporization or condensation"],["Meaning of triple point?","All three phases coexist at equilibrium."],["Beyond the critical point, distinct liquid/gas phases?","No; the substance is supercritical."]]}
]},
{id:"water-solubility",name:"Water, Solubility & Aqueous Behavior",description:"Water polarity, dissolution, solubility rules, electrolytes, precipitation, and concentration ideas.",modules:[
{id:"why-water-dissolves",name:"Why Water Dissolves",type:"Molecular Reasoning",summary:"Connect polarity and ion-dipole attraction to dissolution.",learn:"Water's polar molecules can surround ions and polar molecules, stabilizing dispersed particles.",example:"Na⁺ becomes hydrated by oxygen ends of water molecules.",practice:[["Why does NaCl dissolve in water?","Ion-dipole attractions stabilize separated ions."],["Why is oil poorly soluble in water?","Oil is largely nonpolar while water is strongly polar."],["What is hydration?","Water molecules surrounding dissolved particles."]]},
{id:"solubility-precipitation",name:"Solubility & Precipitation",type:"Prediction",summary:"Predict whether aqueous ions remain dissolved or form a solid.",learn:"Solubility patterns help predict whether ion combinations form insoluble precipitates.",example:"Mixing Ag⁺ and Cl⁻ solutions produces AgCl(s).",practice:[["What visual sign can indicate precipitation?","A solid forms from solution."],["Does every ionic compound dissolve well?","No"],["Why are solubility rules useful?","They predict likely aqueous products and precipitates."]]},
{id:"electrolytes",name:"Electrolytes",type:"Conceptual",summary:"Relate dissolved ions to electrical conductivity.",learn:"Strong electrolytes produce many mobile ions in solution; nonelectrolytes remain mostly molecular.",example:"NaCl(aq) conducts because Na⁺ and Cl⁻ are mobile.",practice:[["Why does sugar solution conduct poorly?","Sugar dissolves as neutral molecules."],["Strong acid solution is generally what type of electrolyte?","Strong electrolyte"],["What carries charge through an aqueous electrolyte?","Mobile ions"]]}
]},
{id:"kinetics",name:"Reaction Rates & Kinetics",description:"Collision theory, activation energy, concentration, temperature, catalysts, and interpreting rate data.",modules:[
{id:"collision-theory",name:"Collision Theory",type:"Conceptual",summary:"Explain why some particle collisions react and others do not.",learn:"Successful collisions require sufficient energy and favorable orientation.",example:"Heating often increases the fraction of collisions energetic enough to react.",practice:[["Two requirements for effective collision?","Sufficient energy and proper orientation"],["Why does higher concentration often increase rate?","More frequent collisions"],["Does every collision form products?","No"]]},
{id:"rate-factors",name:"Factors Affecting Rate",type:"Reasoning",summary:"Predict how temperature, concentration, surface area, and catalysts change reaction speed.",learn:"Rate changes when collision frequency or the fraction of effective collisions changes.",example:"Powdered solid can react faster than a large chunk because more surface is exposed.",practice:[["Effect of increasing temperature?","Usually increases rate"],["Why does powder react faster?","Greater exposed surface area"],["What does a catalyst change?","It provides a lower-activation-energy pathway."]]},
{id:"energy-profile",name:"Activation Energy Profiles",type:"Visual Reasoning",summary:"Read reaction-coordinate diagrams and catalyst effects.",learn:"Activation energy is the energy barrier between reactants and the transition state.",example:"A catalyst lowers the peak without changing the energy difference between reactants and products.",practice:[["Does a catalyst change ΔH?","No"],["What does the peak represent conceptually?","The transition-state energy region"],["Lower activation energy changes rate how?","It increases the rate."]]}
]},
{id:"equilibrium",name:"Chemical Equilibrium",description:"Dynamic equilibrium, equilibrium constants, reaction quotient, and Le Châtelier reasoning.",modules:[
{id:"dynamic-equilibrium",name:"Dynamic Equilibrium",type:"Conceptual",summary:"Understand equal forward and reverse rates without requiring equal concentrations.",learn:"At dynamic equilibrium, forward and reverse reaction rates are equal, so macroscopic concentrations remain constant.",example:"Molecules continue reacting even though measured concentrations stop changing.",practice:[["Are forward and reverse reactions stopped at equilibrium?","No"],["Are reactant and product concentrations necessarily equal?","No"],["What becomes equal?","Forward and reverse rates"]]},
{id:"le-chatelier",name:"Le Châtelier's Principle",type:"Prediction",summary:"Predict how equilibrium responds to concentration, pressure, and temperature changes.",learn:"An equilibrium system responds to a disturbance in a direction that partially counteracts the imposed change.",example:"Adding a reactant commonly shifts toward products if that consumes some added reactant.",practice:[["Add product; typical shift?","Toward reactants"],["Decrease gas volume; shift favors which side?","The side with fewer moles of gas, when applicable."],["Does a catalyst change equilibrium position?","No"]]},
{id:"q-k",name:"Q vs K",type:"Quantitative Reasoning",summary:"Use reaction quotient and equilibrium constant to predict direction.",learn:"If Q<K, reaction proceeds forward toward products; if Q>K, it proceeds in reverse; if Q=K, it is at equilibrium.",example:"Q<K → shift right.",practice:[["Q>K means shift?","Left, toward reactants"],["Q=K means?","System is at equilibrium"],["Does K depend on starting concentrations?","No, at a fixed temperature K is characteristic of the reaction."]]}
]},
{id:"acids-bases",name:"Acids, Bases & pH",description:"Acid-base models, pH, strong/weak behavior, neutralization, titration, and buffers.",modules:[
{id:"acid-base-models",name:"Acid & Base Models",type:"Conceptual",summary:"Recognize proton donors/acceptors and aqueous acid-base behavior.",learn:"In the Brønsted-Lowry model, acids donate H⁺ and bases accept H⁺.",example:"HCl donates H⁺ to water; NH₃ can accept H⁺.",practice:[["Bronsted acid does what?","Donates H⁺"],["Bronsted base does what?","Accepts H⁺"],["Conjugate acid-base pairs differ by what?","One proton"]]},
{id:"ph",name:"pH & Concentration",type:"Quantitative",summary:"Connect hydrogen-ion concentration to the logarithmic pH scale.",learn:"pH = −log[H⁺]. A one-unit pH change corresponds to a tenfold change in [H⁺].",example:"[H⁺]=1×10⁻³ M gives pH 3.",practice:[["[H⁺]=1×10⁻⁵ M. pH?","5"],["pH 3 vs pH 5: which has more H⁺ and by how much?","pH 3 has 100× more H⁺"],["Why is pH not a linear scale?","It is logarithmic."]]},
{id:"neutralization",name:"Neutralization & Titration",type:"Multi-step",summary:"Use stoichiometry to connect acid and base amounts.",learn:"At an equivalence point, stoichiometrically equivalent acid and base quantities have reacted according to the balanced equation.",example:"For monoprotic strong acid/base, moles acid = moles base at equivalence.",practice:[["What determines acid-base mole ratio?","Balanced chemical equation"],["Purpose of indicator?","Signal a pH region near an endpoint"],["Endpoint and equivalence point always identical?","Not exactly; a good indicator makes them close."]]},
{id:"buffers",name:"Buffers",type:"Reasoning",summary:"Explain resistance to pH change.",learn:"A buffer contains components that consume added acid or base, limiting pH change.",example:"Weak acid/conjugate base pairs are common buffers.",practice:[["What does a buffer resist?","Large pH changes"],["Can a buffer absorb unlimited acid/base?","No"],["What happens when buffer capacity is exceeded?","pH can change sharply."]]}
]},
{id:"redox-electrochem",name:"Redox & Electrochemistry",description:"Oxidation states, electron transfer, balancing redox ideas, galvanic cells, and electrochemical reasoning.",modules:[
{id:"oxidation-numbers",name:"Oxidation Numbers",type:"Representation",summary:"Assign oxidation states and identify oxidation/reduction.",learn:"Oxidation is increase in oxidation number; reduction is decrease.",example:"Zn⁰ → Zn²⁺ is oxidation.",practice:[["OIL RIG stands for?","Oxidation Is Loss, Reduction Is Gain (of electrons)"],["Zn 0→+2 is?","Oxidation"],["Cl₂ 0→Cl⁻ −1 is?","Reduction"]]},
{id:"electron-transfer",name:"Redox Reactions",type:"Reasoning",summary:"Track electron loss and gain between species.",learn:"Electrons lost by the reducing agent are gained by the oxidizing agent.",example:"Zn + Cu²⁺ → Zn²⁺ + Cu: Zn oxidizes, Cu²⁺ reduces.",practice:[["Reducing agent is oxidized or reduced?","Oxidized"],["Oxidizing agent does what to another species?","Causes its oxidation by accepting electrons"],["Are electrons conserved in redox?","Yes"]]},
{id:"galvanic-cells",name:"Galvanic Cells",type:"System Reasoning",summary:"Connect spontaneous redox to electron flow through an external circuit.",learn:"Oxidation occurs at the anode and reduction at the cathode. Electrons flow through the wire from anode to cathode.",example:"AN OX, RED CAT: anode oxidation, cathode reduction.",practice:[["Where does oxidation occur?","Anode"],["Electron flow direction?","Anode to cathode"],["Role of salt bridge?","Maintain charge balance by ion migration."]]}
]},
{id:"entropy-free-energy",name:"Entropy & Free Energy",description:"Energy dispersal, spontaneity, enthalpy-entropy competition, and qualitative Gibbs free-energy reasoning.",modules:[
{id:"entropy",name:"Entropy",type:"Conceptual",summary:"Reason about energy dispersal and number of accessible arrangements.",learn:"Entropy often increases when matter or energy becomes more dispersed and when the number of accessible microscopic arrangements grows.",example:"Gas formation often increases entropy relative to condensed phases.",practice:[["More dispersed gas generally has higher or lower entropy than solid?","Higher"],["Does greater particle freedom generally increase entropy?","Yes"],["Is entropy simply 'disorder' in every situation?","No; energy dispersal and microstates are more precise ideas."]]},
{id:"gibbs",name:"Gibbs Free Energy",type:"Reasoning",summary:"Relate enthalpy, entropy, and temperature to spontaneity.",learn:"ΔG = ΔH − TΔS. A negative ΔG indicates thermodynamic favorability under specified conditions.",example:"A process can become favorable at high temperature if positive entropy contribution dominates.",practice:[["ΔG<0 means?","Thermodynamically favorable/spontaneous under the stated conditions"],["Does spontaneous mean fast?","No"],["What separate topic governs speed?","Kinetics"]]},
{id:"thermo-vs-kinetics",name:"Thermodynamics vs Kinetics",type:"Synthesis",summary:"Separate whether a process is favorable from how fast it occurs.",learn:"Thermodynamics addresses energetic favorability; kinetics addresses reaction rate and barriers.",example:"Diamond converting to graphite is thermodynamically favorable under ordinary conditions but extremely slow.",practice:[["Can favorable reaction be slow?","Yes"],["Catalyst mainly affects ΔG or activation energy?","Activation energy"],["Why are thermodynamics and kinetics both needed?","One predicts favorability; the other predicts rate."]]}
]},
{id:"nuclear",name:"Nuclear Chemistry",description:"Radioactivity, nuclear equations, half-life, fission, fusion, and radiation reasoning.",modules:[
{id:"nuclear-symbols",name:"Nuclear Symbols & Decay",type:"Representation",summary:"Balance mass number and atomic number in nuclear equations.",learn:"Nuclear equations conserve total mass number and total atomic number.",example:"Alpha emission lowers mass number by 4 and atomic number by 2.",practice:[["Alpha particle symbol?","⁴₂He"],["Beta-minus changes atomic number by?","+1"],["What must balance in nuclear equations?","Mass number and atomic number"]]},
{id:"half-life",name:"Half-Life",type:"Quantitative",summary:"Model exponential radioactive decay.",learn:"After each half-life, half of the radioactive nuclei from the previous interval remain.",example:"80 g →40→20→10 g after three half-lives.",practice:[["100 g after 2 half-lives?","25 g"],["Does half-life depend on starting amount?","No"],["Shape of decay curve?","Exponential"]]},
{id:"fission-fusion",name:"Fission & Fusion",type:"Conceptual",summary:"Distinguish splitting heavy nuclei from joining light nuclei.",learn:"Fission splits heavy nuclei; fusion joins light nuclei. Both can release large nuclear energy.",example:"Stars are powered primarily by fusion.",practice:[["Process powering Sun?","Fusion"],["Splitting U-235 is?","Fission"],["Why is nuclear energy per reaction large?","Nuclear binding-energy changes involve mass-energy conversion."]]}
]}
];
const seen=new Set(D.topics.map(t=>t.id));moreTopics.forEach(t=>{if(!seen.has(t.id))D.topics.push(t)});

E.phase1={
 benchmark:{name:"Broad high-school/general chemistry benchmark",topicAreas:21,covered:21},
 learningFlow:["Understand","See it","Work it","Practice it","Remember it","Challenge it"],
 formulaCards:[
 ["Density","D = m / V","Mass over volume","Use compatible units; 1 mL = 1 cm³ for volume equivalence."],
 ["Percent error","|experimental − accepted| / accepted × 100%","Distance from accepted value as a percent","Use absolute value for standard percent error."],
 ["Moles & particles","N = nNₐ","moles × Avogadro's number","Nₐ = 6.022 × 10²³ mol⁻¹."],
 ["Molarity","M = n / V","moles per liter","Convert mL to L."],
 ["Dilution","M₁V₁ = M₂V₂","solute moles conserved","Use only for dilution of the same solute."],
 ["Gas relationships","P₁V₁/T₁ = P₂V₂/T₂","combined gas law","Temperature must be Kelvin."],
 ["Heat","q = mcΔT","mass × specific heat × temperature change","Track the sign of ΔT and energy flow."],
 ["pH","pH = −log[H⁺]","logarithmic acidity scale","One pH unit is a tenfold [H⁺] change."],
 ["Free energy","ΔG = ΔH − TΔS","enthalpy-entropy competition","Use absolute temperature."],
 ["Photon relationship","c = λν","wavelength × frequency = speed of light","Use wavelength in meters with c in m/s."],
 ["Average atomic mass","Σ(mass × fractional abundance)","weighted mean","Abundances must sum to 1."],
 ["Percent yield","actual / theoretical × 100%","experimental efficiency","Theoretical yield comes from limiting reactant."]
 ],
 memoryCards:[
 ["AN OX, RED CAT","Anode = oxidation. Cathode = reduction."],
 ["OIL RIG","Oxidation Is Loss, Reduction Is Gain of electrons."],
 ["Long λ, low ν","Wavelength and frequency move opposite ways."],
 ["M over L","Molarity means moles per liter."],
 ["Q vs K","Q<K → right; Q>K → left; Q=K → equilibrium."],
 ["Acid gives, base grabs","Brønsted acid donates H⁺; base accepts H⁺."],
 ["Percent → decimal","Convert isotope percentage abundance before weighted averaging."],
 ["Kelvin for gas laws","Gas-law temperature ratios need an absolute scale."],
 ["Coefficients, never subscripts","Balance equations without changing compound identities."],
 ["Same protons, different neutrons","That is what makes isotopes of one element."]
 ],
 visuals:[
  {id:"density",name:"Density Explorer",kind:"density",topic:"Density",desc:"Hold mass constant and change volume to see density respond."},
  {id:"displacement",name:"Water Displacement",kind:"displacement",topic:"Density",desc:"Drop an object into a cylinder and watch displaced volume become object volume."},
  {id:"sigfig",name:"Significant-Figure Scanner",kind:"sigfig",topic:"Measurement",desc:"Watch meaningful digits separate from placeholder zeros."},
  {id:"isotope",name:"Isotope Weighted-Average Mixer",kind:"isotope",topic:"Atomic Structure",desc:"Change isotope abundance and watch average atomic mass move."},
  {id:"wave",name:"Wavelength ↔ Frequency",kind:"wave",topic:"EM Radiation",desc:"Change wavelength and watch frequency respond inversely."},
  {id:"molarity",name:"Molarity Mixer",kind:"molarity",topic:"Solutions",desc:"Change solute amount and solution volume to visualize concentration."},
  {id:"gas",name:"Gas-Law Piston",kind:"gas",topic:"Gases",desc:"Compress a particle model and watch pressure rise."},
  {id:"heat",name:"Heat Transfer",kind:"heat",topic:"Thermochemistry",desc:"Watch thermal energy move between hot and cold objects."},
  {id:"equilibrium",name:"Dynamic Equilibrium",kind:"equilibrium",topic:"Equilibrium",desc:"See forward and reverse reactions continue while concentrations stabilize."},
  {id:"ph",name:"pH Scale Explorer",kind:"ph",topic:"Acids & Bases",desc:"Move one pH unit and see the tenfold concentration effect."},
  {id:"kinetics",name:"Activation-Energy Path",kind:"kinetics",topic:"Kinetics",desc:"Compare catalyzed and uncatalyzed energy barriers."},
  {id:"phase",name:"Heating Curve",kind:"phase",topic:"States of Matter",desc:"See energy continue entering during temperature plateaus."}
 ]
};
})();